title: Dive into LangGraph
author: Luo Chang
repository:
  url: https://github.com/luochang212/dive-into-langgraph
  path_to_book: .
sphinx:
  config:
    html_baseurl: https://luochang212.github.io/dive-into-langgraph/
exclude_patterns:
  - LICENSE
  - .env.example
  - .gitignore
  - requirements.txt
  - langgraph.json
  - myst.yml
execute:
  execute_notebooks: "off"
